version: '3.7'
services:
  web:
    build: .
    entrypoint: /app/entrypoint.sh
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.11-alpine3.18
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - "5435:5432"
