# Generated by Django 5.0.6 on 2024-05-31 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='cpf')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('dataDeNascimento', models.DateTimeField(verbose_name='data de nascimento')),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10, verbose_name='genero')),
                ('rendaMensal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='renda mensal')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='alterado')),
            ],
        ),
    ]
