# Generated by Django 5.0.6 on 2024-06-04 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='dataDeNascimento',
            new_name='data_de_nascimento',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='rendaMensal',
            new_name='renda_mensal',
        ),
    ]
