# Generated by Django 5.0.6 on 2024-05-31 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='aporte')),
                ('dataDaContratacao', models.DateTimeField(verbose_name='data da contratacao')),
                ('idadeDeAposentadoria', models.IntegerField(verbose_name='idade de aposentadoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='alterado')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_cliente', to='clientes.cliente', verbose_name='cliente')),
                ('idProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_produto', to='produtos.produto', verbose_name='produto')),
            ],
        ),
    ]
