# Generated by Django 5.0.6 on 2024-06-03 01:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('planos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorAporte', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='aporte')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='alterado')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_cliente', to='clientes.cliente', verbose_name='cliente')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes_planos', to='planos.plano', verbose_name='aportes_plano')),
            ],
        ),
    ]
