# Generated by Django 5.0.6 on 2024-06-03 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos', '0002_aporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorResgate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='resgate')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='alterado')),
                ('idPlano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resgates_plano', to='planos.plano', verbose_name='aportes_plano')),
            ],
        ),
    ]
